apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    {{- range .Values.containerPorts }}
    - name: {{ .name }}
      port: {{ .internalPort }}
      protocol: {{ .protocol }}
      targetPort: {{ .externalPort }}
    {{- end }}

